#!/bin/bash -e

prefix=$1
npm_json=$2
outdir=`readlink -f "$3"`
bucket="raven-deploy"

npm_lock=`dirname $npm_json`/npm-shrinkwrap.json
checksum=`md5sum $npm_lock | cut -d' ' -f1`
artifact_filename="${prefix}-${checksum}.tar"
artifact_path="${outdir}/${artifact_filename}"
artifact_s3="s3://${bucket}/npm/${prefix}/${artifact_filename}"

echo "artifact $artifact_path"

# if we don't already have a matching artifact, build one
if [ ! -f "$artifact_path" ]; then
	tmpdir=`mktemp -d`

	cp "$npm_json" "$tmpdir"
	cp "$npm_lock" "$tmpdir"

	pushd "$tmpdir"
	npm install
	tar -c node_modules --exclude-vcs > "$artifact_path"
	popd

	rm -rf $tmpdir
else
	echo "artifact exists. doing nothing"
fi


if ! aws s3 ls "$artifact_s3"; then
	echo "uploading ${artifact_s3}"
	aws s3 cp "${artifact_path}" "${artifact_s3}"
else
	echo "artifact already in s3. not uploading"
fi

#vim:set ft=sh:
